name: BTC Monitor

on:
  schedule:
    - cron: "*/10 * * * *"
    - cron: "5-59/10 * * * *"   # 🔥 extra trigger (important)
  workflow_dispatch:

jobs:
  run-monitor:
    runs-on: ubuntu-latest
    environment: btc-tracker

    steps:
      - uses: actions/checkout@v3

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer

      - run: composer install --no-interaction --prefer-dist --no-progress

      - name: Run monitor
        run: php monitor.php
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          TO_Email:   ${{ secrets.TO_Email }}
